// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 
// good good very good 